### ISSUE TITLE
Satisfiability analysis

### ISSUE THREAD

**Issue by t81lal** [LLVM-but-worse/maple-ir#16] opened 2018-09-27 13:42 UTC
Uber conditional evaluation is possible if satisfiability analysis is implemented.

Consider if (a != b && a == b). Evidently this is impossible. In practice, we would be substituting in possible values from local value analysis into the expression too.
It's easy to hardcode for simple cases but for complex cases it is impossible.

SMT solvers like Z3 are designed to solve satisfiability problems like this so maybe we should consider that. Z3 has a Java API.

**Comment by ecx86** [comment] 2018-09-28 15:31
Duplicate of #2

**Closed by ecx86** 2018-09-28 15:31 UTC
